version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"

  app:
    env_file:
      - .env
    container_name: app
    restart: always
    links:
      - mysql
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
